import { INestApplication } from '@nestjs/common';
import request from 'supertest';
import { DataSource } from 'typeorm';
import { createTestApp, seedClientUser } from './utils/create-test-app';
import { ClientActivityModule } from '../src/client-activity/client-activity.module';
import { Praticien } from '../src/database/entities/praticien.entity';
import { RendezVous } from '../src/database/entities/rendez-vous.entity';
import { Avis } from '../src/database/entities/avis.entity';
import { Paiement } from '../src/database/entities/paiement.entity';
import { Remboursement } from '../src/database/entities/remboursement.entity';

describe('client-activity', () => {
  let app: INestApplication;
  let ds: DataSource;

  beforeAll(async () => {
    app = await createTestApp({ imports: [ClientActivityModule] });
    ds = app.get(DataSource);
  });
  afterAll(async () => { await app.close(); });
  const http = () => request(app.getHttpServer());

  it('GET /api/client/activity requires auth', async () => {
    await http().get('/api/client/activity').expect(401);
  });

  it('merges rendez-vous, avis (matched by full name) and remboursement into one newest-first feed', async () => {
    const seeded = await seedClientUser(app, 'activity-client@aura.io');
    // seedClientUser assigns firstname 'Client', lastname 'Test' -> full name 'Client Test'
    const praticien = await ds.getRepository(Praticien).save({
      firstname: 'Elodie', lastname: 'Marceau', email: 'activity-prat@x.io', telephone: '06',
      ville: 'Nice', niveau: 'n', specialite: 's', mode: 'm', status: 'actif',
      tarif: 50, experience: 3, bio: 'b'.repeat(60), statut_verification: 'valide',
    });

    // Oldest: rendez-vous (2020), then avis (2021); remboursement.created_at is autogenerated
    // "now" so it is always the newest of the three — this keeps the expected order
    // deterministic without needing to control a CreateDateColumn's value directly.
    // 'Z' suffix is required: a bare 'YYYY-MM-DDTHH:mm:ss' string is parsed in the *local*
    // timezone by `new Date(...)`, which would shift the UTC instant compared against below
    // by the host's UTC offset. Date.UTC(...) elsewhere in this file needs no such suffix.
    await ds.getRepository(RendezVous).save({
      client_id: seeded.client.id, praticien_id: praticien.id,
      date_heure: new Date('2020-01-01T10:00:00Z'),
      duree_minutes: 60, mode: 'présentiel', statut: 'termine', tarif: 50,
    });
    await ds.getRepository(Avis).save({
      full_name_author: 'Client Test', praticien_id: praticien.id, note: 5,
      avis: 'a'.repeat(10), date_ajout: new Date('2021-06-01T10:00:00Z'), statut: 'publié',
    });
    const paiement = await ds.getRepository(Paiement).save({
      reference: 'TX-ACTIVITY-1', client_id: seeded.client.id, montant_brut: 50, commission: 5,
      montant_net_praticien: 45, moyen_paiement: 'Carte', statut: 'rembourse',
      date_paiement: new Date('2020-01-01T10:00:00Z'),
    });
    await ds.getRepository(Remboursement).save({
      reference: 'RMB-ACTIVITY-1', client_id: seeded.client.id, paiement_id: paiement.id,
      montant: 50, motif: 'Annulation', statut: 'approuve',
    });

    // Noise: another client's data must never leak into this feed.
    const other = await seedClientUser(app, 'activity-other@aura.io');
    await ds.getRepository(RendezVous).save({
      client_id: other.client.id, praticien_id: praticien.id,
      date_heure: new Date('2022-01-01T10:00:00Z'),
      duree_minutes: 60, mode: 'présentiel', statut: 'termine', tarif: 50,
    });

    const res = await http().get('/api/client/activity')
      .set('Authorization', `Bearer ${seeded.token}`).expect(200);
    expect(res.body.status).toBe('success');
    const data = res.body.data;
    expect(data).toHaveLength(3);
    expect(data.map((d: any) => d.type)).toEqual(['remboursement', 'avis', 'rendez_vous']);
    expect(data[0]).toMatchObject({ type: 'remboursement', label: 'Demande de remboursement — approuve' });
    expect(data[1]).toMatchObject({ type: 'avis', label: 'Vous avez laissé un avis', at: '2021-06-01T10:00:00.000Z' });
    expect(data[2]).toMatchObject({
      type: 'rendez_vous', label: 'Séance avec Elodie — termine', at: '2020-01-01T10:00:00.000Z',
    });
    // Sorted newest-first: each `at` strictly decreases down the list.
    const times = data.map((d: any) => new Date(d.at).getTime());
    expect(times).toEqual([...times].sort((a, b) => b - a));
  });

  it('caps the feed at 15 items, keeping the most recent', async () => {
    const seeded = await seedClientUser(app, 'activity-cap@aura.io');
    const praticien = await ds.getRepository(Praticien).save({
      firstname: 'Marc', lastname: 'Lemoine', email: 'activity-cap-prat@x.io', telephone: '06',
      ville: 'Nantes', niveau: 'n', specialite: 's', mode: 'm', status: 'actif',
      tarif: 50, experience: 3, bio: 'b'.repeat(60), statut_verification: 'valide',
    });

    // seedClientUser hardcodes every client's name to 'Client Test', so the avis seeded by the
    // previous test (matched by that same full name — the app-wide, acknowledged limitation of
    // full-name-based avis ownership) is visible here too. Dating every row in 2030 keeps this
    // test's top-15 window unambiguously above that (and any other fixture's) 'at', so the
    // assertions below stay about rendez-vous capping specifically.
    const rows = Array.from({ length: 20 }, (_, i) => ({
      client_id: seeded.client.id,
      praticien_id: praticien.id,
      date_heure: new Date(Date.UTC(2030, 0, i + 1, 10, 0, 0)),
      duree_minutes: 60,
      mode: 'présentiel',
      statut: 'termine',
      tarif: 50,
    }));
    await ds.getRepository(RendezVous).save(rows);

    const res = await http().get('/api/client/activity')
      .set('Authorization', `Bearer ${seeded.token}`).expect(200);
    const data = res.body.data;
    expect(data).toHaveLength(15);
    // The 15 most recent of the 20 seeded days: Jan 6 .. Jan 20 2030 (UTC), newest first.
    expect(data[0].at).toBe(new Date(Date.UTC(2030, 0, 20, 10, 0, 0)).toISOString());
    expect(data[14].at).toBe(new Date(Date.UTC(2030, 0, 6, 10, 0, 0)).toISOString());
    expect(data.every((d: any) => d.type === 'rendez_vous')).toBe(true);
  });
});
